import "@hotwired/turbo-rails"
import "controllers/application"
import "bootstrap"
import "hamburger"
import "plans/init_map"
import "plans/navibar"
import "plans/create_plan_trigger"
import "plans/render_plan_markers"